### ISSUE TITLE
Tests failed when built against fmt 7.0.0

### ISSUE THREAD

**Issue by xvitaly** [gabime/spdlog#1611] opened 2020-07-07 14:29 UTC
Some tests failed when built against fmt 7.0.0.

Spdlog version 1.6.1 with backported 22bee8128a4150ce37cf761ed9a609ad891848a6 commit.

Full log:

```text
Test project /builddir/build/BUILD/spdlog-1.6.1/x86_64-redhat-linux-gnu
    Start 1: spdlog-utests
1/1 Test #1: spdlog-utests ....................***Exception: SegFault  1.55 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spdlog-utests is a Catch v2.8.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
to_hex
-------------------------------------------------------------------------------
../tests/test_misc.cpp:143
...............................................................................

../tests/test_misc.cpp:143: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  25 |  24 passed | 1 failed
assertions: 119 | 118 passed | 1 failed



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.55 sec

The following tests FAILED:
          1 - spdlog-utests (SEGFAULT)
Errors while running CTest
```

**Comment by kekePower** [comment] 2020-07-08 09:27
Getting the same on Mageia Cauldron x86_64. Also using the same commit for fmt.

```
+ ctest --output-on-failure
Test project /mgarepo/fmt/deps/spdlog/BUILD/spdlog-1.6.1/build
    Start 1: spdlog-utests
1/1 Test #1: spdlog-utests ....................***Exception: SegFault  1.29 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spdlog-utests is a Catch v2.8.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
to_hex
-------------------------------------------------------------------------------
../tests/test_misc.cpp:143
...............................................................................

../tests/test_misc.cpp:143: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  25 |  24 passed | 1 failed
assertions: 119 | 118 passed | 1 failed



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.29 sec

The following tests FAILED:
	 1 - spdlog-utests (SEGFAULT)
Errors while running CTest
error: Bad exit status from /mgarepo/fmt/deps/spdlog/BUILDROOT/rpm-tmp.TBskk4 (%check)


RPM build errors:
    Bad exit status from /mgarepo/fmt/deps/spdlog/BUILDROOT/rpm-tmp.TBskk4 (%check)
error: failed!
```

**Comment by lgbaldoni** [comment] 2020-07-08 11:42
Same problem with openSUSE Tumbleweed, see [log](https://github.com/gabime/spdlog/files/4890387/spdlog161_fmt7_tests.txt).

**Comment by gabime** [comment] 2020-07-08 11:44
Can we get a stack trace from the coredump?

**Comment by lgbaldoni** [comment] 2020-07-08 12:14
Hope [this](https://github.com/gabime/spdlog/files/4890539/spdlog161_tests_gdb.txt) helps!

**Comment by gabime** [comment] 2020-07-08 12:54
I see it uses /usr/include/fmt/core.h
Does this file belongs to fmt version 7.0?

**Comment by lgbaldoni** [comment] 2020-07-08 13:02
> I see it uses /usr/include/fmt/core.h
> Does this file belongs to fmt version 7.0?

7.0.1 to be precise

**Comment by gabime** [comment] 2020-07-08 13:12
Might be an issue with fmt.. @vitaut please advice

**Comment by vitaut** [comment] 2020-07-08 13:24
This is incorrect:

https://github.com/gabime/spdlog/blob/c62ba5f48db2520e7d2ddbaf14a88ab6f6991894/include/spdlog/fmt/bin_to_hex.h#L95

because it may dereference past the end of the format string. Should be something like

```c++
        while (it != ctx.end() && *it != '}')
```

**Comment by gabime** [comment] 2020-07-08 15:43
Thanks @vitaut

**Comment by gabime** [comment] 2020-07-08 15:52
@lgbaldoni could you verify that latest commit  (19f280466195f347f3f2c474556a6be0b343a7fb) solves it?

**Comment by kekePower** [comment] 2020-07-08 16:26
I can confirm that it compiles successfully andthe test completes without errors.

**Comment by gabime** [comment] 2020-07-08 16:31
Great. Closing..

**Closed by gabime** 2020-07-08 16:31 UTC

**Comment by lgbaldoni** [comment] 2020-07-08 16:41
I can also confirm the problem is solved.

**Comment by xvitaly** [comment] 2020-07-08 16:43
I can confirm too.

Btw, @gabime can you push a new release with this fixes?

**Comment by gabime** [comment] 2020-07-08 16:56
@xvitaly sure, will be released soon
