### ISSUE TITLE
The spdlog project compile problem

### ISSUE THREAD

**Issue by jirotao** [gabime/spdlog#754] opened 2018-07-17 06:37 UTC
I used Visual Studio 2013 to compile example project was faild and Visual Studio 2017  compile success . what caused it ?

**Comment by gabime** [comment] 2018-07-17 08:54
It was fixed in the v1.x branch. Please try

**Comment by jirotao** [comment] 2018-07-18 06:32
<img width="937" alt="_20180718140754" src="https://user-images.githubusercontent.com/30790340/42863961-5d70a774-8a97-11e8-9d7b-a678274587f3.png">

you can see what reason compile faild

**Comment by gabime** [comment] 2018-07-19 11:35
I cannot reproduce this. Works in my vs 2013.

**Closed** 2018-07-19 11:35 UTC
Labels: invalid
