### ISSUE TITLE
[1.3.1] syslog formatting (request) 

### ISSUE THREAD

**Issue by kasru** [gabime/spdlog#1107] opened 2019-06-12 07:49 UTC
spdlog 1.3.1 does not write formatted messages to syslog. 
What recommended ways for write formatted messages like to file or stdout?

**Comment by gabime** [comment] 2019-06-12 09:54
Duplicate of https://github.com/gabime/spdlog/issues/729

**Comment by gabime** [comment] 2019-06-18 21:55
Implemented with additional boolean to ctor (true to format).

**Closed by gabime** 2019-06-18 21:55 UTC
Labels: enhancement
