### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value

### ISSUE THREAD

**Issue by gocarlos** [gabime/spdlog#1282] opened 2019-10-23 14:57 UTC
there seems to be an issue with the logger initialization

minimal example:
```cpp
#include <memory>

#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/spdlog.h"

int main()
{
    auto stack_logger = spdlog::stdout_color_mt("asdf");
}
```
add to cmake
```cmake
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=memory  -g")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=memory  -g")
set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=memory  ")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=memory")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -fsanitize=memory")


add_executable(main main.cpp)
target_link_libraries(main
                      spdlog::spdlog)
```

the memory sanitzer only works with clang

```bash
export CC=clang-8
export CXX=clang++-8
rm -rf _build
mkdir _build
cd _build
cmake .. -DSPDLOG_BUILD_TESTS=OFF -DSPDLOG_BUILD_EXAMPLES=OFF -DSPDLOG_BUILD_BENCH=OFF
make -j main
```

clang sanitizer output
```txt
==7676==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5a250d in spdlog::pattern_formatter::compile_pattern_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/ladmin/git/spdlog/include/spdlog/details/pattern_formatter-inl.h:1278:13
    #1 0x5a2130 in spdlog::pattern_formatter::pattern_formatter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::pattern_time_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /home/ladmin/git/spdlog/include/spdlog/details/pattern_formatter-inl.h:996:5
    #2 0x5b6350 in std::unique_ptr<spdlog::pattern_formatter, std::default_delete<spdlog::pattern_formatter> > spdlog::details::make_unique<spdlog::pattern_formatter, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, spdlog::pattern_time_type const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, spdlog::pattern_time_type const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/ladmin/git/spdlog/include/spdlog/common.h:236:35
    #3 0x5a354f in spdlog::pattern_formatter::clone() const /home/ladmin/git/spdlog/include/spdlog/details/pattern_formatter-inl.h:1012:12
    #4 0x5976bc in spdlog::details::registry::initialize_logger(std::shared_ptr<spdlog::logger>) /home/ladmin/git/spdlog/include/spdlog/details/registry-inl.h:60:43
    #5 0x723ab7 in std::shared_ptr<spdlog::logger> spdlog::synchronous_factory::create<spdlog::sinks::ansicolor_stdout_sink<spdlog::details::console_mutex>, spdlog::color_mode&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::color_mode&) /home/ladmin/git/spdlog/include/spdlog/details/synchronous_factory.h:20:39
    #6 0x7237a4 in std::shared_ptr<spdlog::logger> spdlog::stdout_color_mt<spdlog::synchronous_factory>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, spdlog::color_mode) /home/ladmin/git/spdlog/include/spdlog/sinks/stdout_color_sinks-inl.h:18:12
    #7 0x5958fc in main /home/ladmin/git/spdlog/main.cpp:13:20
    #8 0x7ffff6a44b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #9 0x51a259 in _start (/home/ladmin/git/build-spdlog-clang-Debug/main+0x51a259)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/ladmin/git/spdlog/include/spdlog/details/pattern_formatter-inl.h:1278:13 in spdlog::pattern_formatter::compile_pattern_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

**Comment by gabime** [comment] 2019-10-23 19:31
This is probably false positive and duplicate of https://github.com/gabime/spdlog/issues/680

**Closed** 2019-10-24 13:09 UTC
