### ISSUE TITLE
Crash when using spdlog as shared library - libstd++ complains

### ISSUE THREAD

**Issue by DinoMalpera** [gabime/spdlog#2663] opened 2023-03-01 22:51 UTC
### Steps to reproduce

1. Clone spdlog (d07e8cb576ccb5533f479dd1258e5b609ab010a6)
2. `cmake -DSPDLOG_BUILD_SHARED=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -B build -S .`
3. `cd build`
`sudo cmake --build . --target install`
4. CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.22)
project(untitled9 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_DEBUG")

find_package(spdlog REQUIRED)

add_executable(untitled9 main.cpp)

target_link_libraries( untitled9
        PRIVATE spdlog::spdlog )
```
5. main.cpp:
```c++
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

int
main()
{
    auto logger = spdlog::basic_logger_st("mylogger", "log.txt");
    logger->error( "Haowhe" );

    return 0;
}
```
### Error on run
**untitled9: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.**

### Packages
`g++-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0`
`libstdc++-12-dev 12.1.0-2ubuntu1~22.04`

### Related
Possibly related to #2113 

### Workaround
Works fine when linking spdlog as a static library.
Works fine when `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_DEBUG")` is commented out.

**Comment by gabime** [comment] 2023-03-01 23:00
possible duplicate of #2145

**Comment by DinoMalpera** [comment] 2023-03-01 23:05
I don't know if it's an fmt issue (as indicated in #2145).
When I debug it crashes [here](https://github.com/gabime/spdlog/blob/d07e8cb576ccb5533f479dd1258e5b609ab010a6/include/spdlog/details/registry-inl.h#L47).

**Closed as completed** 2023-03-10 16:56 UTC
