### ISSUE TITLE
Issue with creating a Asynchronous log.  

### ISSUE THREAD

**Issue by evandam1999** [gabime/spdlog#973] opened 2019-01-19 22:36 UTC
std::shared_ptr<spdlog::logger> my_logger;
my_logger = spdlog::basic_logger_mt<spdlog::async_factory>("async_file_logger", "logs/async_log.txt");

Having an issue with the following code.  It is just never returning from the basic_logger_mt call.  Looks to me like it is somewhere around the thread pool creation.  The logger is being created in a dll plugin that is being loaded from the main exe.  I thought it might be the windows issue with application deadlock, but this is not happening on exit. 

Any Ideas ?

**Comment by gabime** [comment] 2019-01-27 17:17
@evandam1999 Did you find a solution?

**Comment by evandam1999** [comment] 2019-01-27 20:54
I did, turns out that I was doing the creation of the logger in a constructor and it did not like that.  

Erick

**Comment by gabime** [comment] 2019-01-27 20:56
ok, good. will close it..

**Comment by vigsterkr** [comment] 2020-02-20 07:20
i'd like to reopen this one as i'm currently having the very same behaviour. want to use async logging and creating the spdlog::thread_pool within a ctor of a class that holds the reference to the thread pool... basically the ctor of thread_pool never returns.

i'm testing this with MSVC 2017 and spdlog 1.3.1 atm... will try to update to the latest spdlog, maybe that helps.

**Comment by vigsterkr** [comment] 2020-02-20 07:35
just for future reference this is where msvc gets stuck: https://github.com/gabime/spdlog/blob/v1.3.1/include/spdlog/details/thread_pool.h#L136

i realize that this codebase has changed somewhat since then and currently testing it locally...

**Comment by tt4g** [comment] 2020-02-20 09:11
@vigsterkr For your information.

I had a similar experience before.

The cause is unknown, but when the debugger is attached by MSVC 2017, it crashes in the move constructor (`std::thread(std::thread &&) noexcept`).
It may be the same problem as this link: [SetUnhandledExceptionFilter callback not invoked from thread with lambda \- Developer Community](https://developercommunity.visualstudio.com/content/problem/235602/setunhandledexceptionfilter-callback-not-invoked-f.html)

When I set the build type to Release, the problem no longer appeared.
Please try to reproduce it in the Release build.

**Comment by tt4g** [comment] 2020-02-20 09:12
It may be the same problem as this link: [std::thread with lambda crashes when compiled without /GL in a project that uses /GL everywhere \- Developer Community](https://developercommunity.visualstudio.com/content/problem/701555/stdthread-with-lambda-crashes-when-compiled-withou.html)

**Comment by vigsterkr** [comment] 2020-02-20 12:20
@tt4g thnx for the comments... currently i'm trying to test the same code with 1.5.0 but linking against the libspdlog.lib (i.e. static lib) seems to be broken, as i'm getting a lot of undefined references :(

i've tried both debug and release builds...

**Comment by vigsterkr** [comment] 2020-02-20 12:38
ok so finally managed to get the 1.5.0 working, and i can confirm that the very same bug exists, and it happens at the very same place, i.e. when the emplace_back is called on the threads_ vector: https://github.com/gabime/spdlog/blob/v1.5.0/include/spdlog/details/thread_pool-inl.h#L26

hence @gabime i'd like to have this issue reopened, as it's easy to reproduce on windows with MSVC (see above)

**Comment by vigsterkr** [comment] 2020-02-20 12:40
@tt4g this happens without attaching the debugger, i.e. i have a very simple command line test for this, and when i run that executable from the command line the executable is stuck at ctoring the threadpool, the CPU load is 0 of the process, but the only way to get back the shell is to kill the process... basically nothing happens it gets stuck with the thread_pool ctor.

**Comment by gabime** [comment] 2020-02-20 12:45
> It's easy to reproduce on windows with MSVC (see above)

Could you post example code to reproduce?

**Comment by vigsterkr** [comment] 2020-02-20 12:56
```
class IO {
public:
    IO () {
       thread_pool = std::make_shared<spdlog::details::thread_pool>(128, 1);
    }

private:
      std::shared_ptr<spdlog::details::thread_pool> thread_pool;
};

class Env {
public:
   static Env* instance() {
     static Env env {};
     return &env; 
    }
private:
   Env::Env() {
    io = std::make_unique<IO>();
   }
private:
   std::unique_ptr<IO> io;
};

int main(int argc, char** argv)
{
    auto env = Env::instance();

    return 0;
}
```

**Comment by vigsterkr** [comment] 2020-02-20 12:56
@gabime this is roughly the main idea what's happening in my codebase... and the thread_pool shared_ptr creation is getting stuck...

**Comment by vigsterkr** [comment] 2020-02-20 13:00
@tt4g just tested with release, everything is the very same as in case of debug

**Comment by vigsterkr** [comment] 2020-02-20 13:09
@gabime i have msvc 17 on my local machine, but the above codebase - a bit more complicated - is being tested with MSVC 19 and AFAIK it does behave the same way. although i'm no 100% sure about this, so it should be tested! i've seen these sorts of behaviors disappear in later releases of VC++

**Comment by vigsterkr** [comment] 2020-02-20 13:23
here's a super simplified version of this thing on godbolt, of course some crucial stuff are missing actually from thread_pool, and the problem is that this only tests compilation not running: https://godbolt.org/z/kzFwF5

and as noted above in my case everything compiles perfectly, but it gets stuck at runtime

**Comment by vigsterkr** [comment] 2020-02-20 13:27
dunno what's the version here of vc, but here the code from godbolt (note the thread_pool only creates a simple vector of threads), does not return with 0 if i dont comment out the thread_pool creation: https://rextester.com/l/cpp_online_compiler_visual

**Comment by tt4g** [comment] 2020-02-20 13:51
I create reproduce project: https://github.com/tt4g/spdlog-issue-973
However, I cannot reproduce crash with Visual Studio 2017 (15.9.20).
Sorry, Now that I have no time to build a static library, I use a header library.

```bash
$ build\Debug\spdlog_issue_973.exe
$ echo %errorlevel%
0
$ build\Release\spdlog_issue_973.exe
$ echo %errorlevel%
0
```

@vigsterkr Could you try to reproduce the problem with this project?

**Comment by vigsterkr** [comment] 2020-02-20 14:14
👍 although it might be important to note that that codeset is not in the executable but in a dll that is being loaded runtime. in 2h i'll try this codebase as well as i might send you some patches if i can make that simple one fully reproduce the scenario i'm facing atm

**Comment by tt4g** [comment] 2020-02-20 21:56
Windows often causes crashes when creating and destroying threads in DLL.
I don't think the problem can be reproduced without a more complete sample of your DLL and application.

**Comment by vigsterkr** [comment] 2020-02-21 11:39
ok so i digged around and debugged and basically this is exactly what's happening in my case: https://stackoverflow.com/a/25746044/2798875

afaik this could be only fixed in spdlog if one would start using native threads and not std::thread.... note that either you decide to fix it... or not. if not it would be worth to have a wiki somewhere that describes that one should not use thread_pool in this specific scenario

**Comment by gabime** [comment] 2020-02-21 11:46
Thx. How the symbol visibility link is related to this?

**Comment by vigsterkr** [comment] 2020-02-21 11:55
@gabime lol sorry i meant this linke (edited above) https://stackoverflow.com/a/32272900/2798875

**Comment by gabime** [comment] 2020-02-21 12:04
So in your specific case the issue is creating the thread from DllMain?

**Comment by vigsterkr** [comment] 2020-02-21 12:14
yep coz i have a static var that is being ctored on dllmain that actually kicks in the Env creation (see the example above) and from then on its all clear ;P

**Comment by gabime** [comment] 2020-02-21 12:19
Right. I think it deserves an entry in the FAQ section..

**Comment by tt4g** [comment] 2020-02-21 12:27
Thread creation calls and synchronous processing from DLLMain can cause problems.
I guess it is one of the following two cases:

[Dynamic\-Link Library Best Practices \- Win32 apps \| Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices):

> * Synchronize with other threads. This can cause a deadlock.

> * Call CreateThread. Creating a thread can work if you do not synchronize with other threads, but it is risky.

**Comment by gabime** [comment] 2020-02-21 12:30
@vigsterkr What i don't understand is that according to your example the ::instance() implementation is actually lazy(creates and returns the instance on first call).. so should have worked..

**Comment by vigsterkr** [comment] 2020-02-21 12:43
@gabime true but i wasn't 100% with that example... there's another static var creation in some other parts of the code that actually calls this lazy creation... hence when you load in the dll, that static var creation is triggered and then things escalates

**Comment by gabime** [comment] 2020-02-27 11:57
Closed. Updated the FAQ in the wiki about how to avoid this.

**Closed by gabime** 2020-02-27 11:57 UTC
