### ISSUE TITLE
warnings conversion 'size_t' to 'int' on windows

### ISSUE THREAD

**Issue by LaoTszy** [gabime/spdlog#119] opened 2015-08-07 07:45 UTC
spdlog\details\format.cc(636): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
spdlog\details\format.cc(642): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
spdlog\details\format.cc(656): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
spdlog\details\format.cc(661): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

**Comment by gabime** [comment] 2015-08-07 10:14
I cannot reproduce this. What version of spdlog do you use?

**Comment by LaoTszy** [comment] 2015-08-07 11:42
That's more the question for which platform you build it. The warning
appears if you build for x64 in windows, so that sizeof(size_t) is larger
than sizeof(int) and FMT_USE_WINDOWS_H is defined.

Cheers,
Lao

**Comment by gabime** [comment] 2015-08-07 12:19
Ok. I will open an issue in cppformat project

**Comment by gabime** [comment] 2015-08-14 17:31
Fixed in f8b728ea8a5ea5b10148b69737f88e8c11909673

**Closed by gabime** 2015-08-14 17:31 UTC
