### ISSUE TITLE
MSVC 17.6.2 unable to use function call returning const char* or std::string_view as argument to logging function call

### ISSUE THREAD

**Issue by tksuoran** [gabime/spdlog#2743] opened 2023-05-27 16:32 UTC
After updating to VS 2022 17.6.2, I get compiler errors when I try to use function call returning `const char*` or `std::string_view` into logging function argument.

I am using spdlog via cmake fetchcontent using `v1.x` tag which currently gives me `ea1af20840dd052b368a5f24630426709409a7a5`.
I am using libfmt via cmake fetchcontent using `171a020c828669490b98af0c2640e50f1511d2cc` (latest commit at the time of writing this issue).

The error I get:
```
spdlog-src\include\spdlog\logger.h(374): error C2664: 'fmt::v10::format_arg_store<fmt::v10::format_context,const char *> fmt::v10::make_format_args<fmt::v10::format_context,_Ty>(_Ty &)': cannot convert argument 1 from '_Ty' to '_Ty &'
  with
  [
      _Ty=const char *
  ] (compiling source file erhe\gl\gl_helpers.cpp)
fmt-src\include\fmt\core.h(1804): note: see declaration of 'fmt::v10::make_format_args' (compiling source file erhe\gl\gl_helpers.cpp)
spdlog-src\include\spdlog\logger.h(374): note: while trying to match the argument list '(_Ty)'
  with
  [
      _Ty=const char *
  ] (compiling source file erhe\gl\gl_helpers.cpp)
spdlog-src\include\spdlog\logger.h(90): note: see reference to function template instantiation 'void spdlog::logger::log_<_Ty>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,_Ty &&)' being compiled
  with
  [
      _Ty=const char *
  ] (compiling source file erhe\gl\gl_helpers.cpp)
spdlog-src\include\spdlog\logger.h(96): note: see reference to function template instantiation 'void spdlog::logger::log<_Ty>(spdlog::source_loc,spdlog::level::level_enum,fmt::v10::basic_format_string<char,const char *>,_Ty &&)' being compiled
  with
  [
      _Ty=const char *
  ] (compiling source file erhe\gl\gl_helpers.cpp)
spdlog-src\include\spdlog\logger.h(170): note: see reference to function template instantiation 'void spdlog::logger::log<_Ty>(spdlog::level::level_enum,fmt::v10::basic_format_string<char,const char *>,_Ty &&)' being compiled
  with
  [
      _Ty=const char *
  ] (compiling source file erhe\gl\gl_helpers.cpp)
erhe\gl\gl_helpers.cpp(49): note: see reference to function template instantiation 'void spdlog::logger::error<const char*>(fmt::v10::basic_format_string<char,const char *>,const char *&&)' being compiled
```

The offending code - which used to work before:
```C++
enum class Error_code : unsigned int;
auto c_str(const Error_code value) -> const char*;
std::shared_ptr<spdlog::logger> log_gl;
...
auto error_code = static_cast<gl::Error_code>(gl::glGetError());
...
log_gl->error("{}", gl::c_str(error_code));
```
If I replace the last line with
```
const char* message = gl::c_str(error_code);
log_gl->error("{}", message);
```
the error does not happen. Unfortunately I get similar issue in many, many places - as if I can no longer put function calls that return `const char*` into arguments for spdlog logging functions. And I get the same issue with functions returning `std::string_view` as well

I will try to make a simple repro.

**Comment by gabime** [comment] 2023-05-27 16:39
Might be fmt 10 issue. Could you try with bundled fmt?

**Comment by tksuoran** [comment] 2023-05-27 16:41
Simpler repro:
```C++
#include <fmt/core.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/base_sink.h>
#include <spdlog/sinks/msvc_sink.h>
#include <memory>

const char* hello_world() { return "Hello, World!"; }

int main()
{
	auto sink_msvc = std::make_shared<spdlog::sinks::msvc_sink_mt>();
	auto logger = std::make_shared<spdlog::logger>(
		"logger",
		spdlog::sinks_init_list{sink_msvc}
	);
	spdlog::register_logger(logger);
	logger->error("{}", hello_world);
	return 0;
}
```
Result:
```
fmt-src\include\fmt\core.h(2523): error C2039: 'parse': is not a member of 'fmt::v10::formatter<const char *(void),Char,void>'
        with
        [
            Char=char
        ]
fmt-src\include\fmt\core.h(1697): note: see declaration of 'fmt::v10::formatter<const char *(void),Char,void>'
        with
        [
            Char=char
        ]
fmt-src\include\fmt\core.h(2580): note: see reference to function template instantiation 'const Char *fmt::v10::detail::parse_format_specs<const char*(void),fmt::v10::detail::compile_parse_context<Char>>(ParseContext &)' being compiled
        with
        [
            Char=char,
            ParseContext=fmt::v10::detail::compile_parse_context<char>
        ]
fmt-src\include\fmt\core.h(2578): note: while compiling class template member function 'fmt::v10::detail::format_string_checker<Char,const char *(void)>::format_string_checker(fmt::v10::basic_string_view<Char>)'
        with
        [
            Char=char
        ]
fmt-src\include\fmt\core.h(2723): note: see reference to class template instantiation 'fmt::v10::detail::format_string_checker<Char,const char *(void)>' being compiled
        with
        [
            Char=char
        ]
main.cpp(17): note: see reference to function template instantiation 'fmt::v10::basic_format_string<char,const char *(__cdecl &)(void)>::basic_format_string<char[3],0>(const S (&))' being compiled
        with
        [
            S=char [3]
        ]
```

**Comment by tksuoran** [comment] 2023-05-27 16:43
I would love to try to use the bundled fmt, but I am not sure how to make it happen in my project because I am using cmake fetchcontent. Even if I don't modify `SPDLOG_FMT_EXTERNAL`, fmt ends up being from what I get with fetchcontent.

What tag / commit is the bundled fmt? I could make my cmake fetchcontent for fmt to point to same version.

**Comment by gabime** [comment] 2023-05-27 16:44
fmt version 9.1.0

**Comment by tksuoran** [comment] 2023-05-27 16:45
I am concerned that it will have other issues with latest MSVC but I will give it a try.

**Comment by tksuoran** [comment] 2023-05-27 16:51
Result using fmt 9.1.0:

```C++
1>main.cpp
1>C:\git\tksuoran\erhe\build\_deps\fmt-src\include\fmt\core.h(2746): error C2039: 'parse': is not a member of 'fmt::v9::detail::fallback_formatter<stripped_type,char_type,void>'
1>C:\git\tksuoran\erhe\build\_deps\fmt-src\include\fmt\core.h(2745): note: see declaration of 'fmt::v9::detail::fallback_formatter<stripped_type,char_type,void>'
1>C:\git\tksuoran\erhe\build\_deps\fmt-src\include\fmt\core.h(2954): note: see reference to function template instantiation 'const char *fmt::v9::detail::parse_format_specs<const char*(void),fmt::v9::detail::compile_parse_context<Char,ErrorHandler>>(ParseContext &)' being compiled
1>        with
1>        [
1>            Char=char,
1>            ErrorHandler=fmt::v9::detail::error_handler,
1>            ParseContext=fmt::v9::detail::compile_parse_context<char,fmt::v9::detail::error_handler>
1>        ]
1>C:\git\tksuoran\erhe\build\_deps\fmt-src\include\fmt\core.h(2951): note: while compiling class template member function 'fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,const char *(void)>::format_string_checker(fmt::v9::basic_string_view<Char>,ErrorHandler)'
1>        with
1>        [
1>            Char=char,
1>            ErrorHandler=fmt::v9::detail::error_handler
1>        ]
1>C:\git\tksuoran\erhe\build\_deps\fmt-src\include\fmt\core.h(3159): note: see reference to class template instantiation 'fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,const char *(void)>' being compiled
1>        with
1>        [
1>            Char=char
1>        ]
1>C:\git\tksuoran\erhe\src\editor\main.cpp(17): note: see reference to function template instantiation 'fmt::v9::basic_format_string<char,const char *(__cdecl &)(void)>::basic_format_string<char[3],0>(const S (&))' being compiled
1>        with
1>        [
1>            S=char [3]
1>        ]
```

**Comment by tksuoran** [comment] 2023-05-27 16:53
My repro is flawed, sorry about that. Fixing.

**Comment by ghost** [comment] 2023-05-27 16:54
I have a similar problem and the visual studio MSVC compiler just fails with error C1001 in the bundled ostream.h file on line 39 `  using result = decltype(test<T>(0));` in the is_streamable class. On Visual Studio 17.5 this error didn't happen.

**Comment by tksuoran** [comment] 2023-05-27 16:55
Using fmt 9.1.0 all my code works fine.

**Comment by gabime** [comment] 2023-05-27 16:59
Possibly duplicate of https://github.com/gabime/spdlog/issues/2719

**Closed as completed** 2023-06-01 21:04 UTC
