### ISSUE TITLE
No function "GetDynamicTimeZoneInformation"

### ISSUE THREAD

**Issue by oconnore** [gabime/spdlog#144] opened 2015-11-13 22:32 UTC
```
/mingw64/bin/g++.exe -Iinclude -I../../lib-ext/g3log/src/ -I../../lib-ext/spdlog/include -std=c++14 -c -o obj/cpp/System.o src/System.cc
In file included from ../../lib-ext/spdlog/include/spdlog/sinks/../details/pattern_formatter_impl.h:36:0,
                 from ../../lib-ext/spdlog/include/spdlog/sinks/../formatter.h:57,
                 from ../../lib-ext/spdlog/include/spdlog/sinks/base_sink.h:36,
                 from ../../lib-ext/spdlog/include/spdlog/logger.h:36,
                 from ../../lib-ext/spdlog/include/spdlog/spdlog.h:33,
                 from include/System.h:8,
                 from src/System.cc:1:
../../lib-ext/spdlog/include/spdlog/sinks/../details/./os.h: In function 'int spdlog::details::os::utc_minutes_offset(const tm&)':
../../lib-ext/spdlog/include/spdlog/sinks/../details/./os.h:170:52: error: 'GetDynamicTimeZoneInformation' was not declared in this scope
     auto rv = GetDynamicTimeZoneInformation(&tzinfo);
                                                    ^
```

**Comment by gabime** [comment] 2015-11-13 23:03
duplicate of #85

**Closed by gabime** 2015-11-13 23:03 UTC
