### ISSUE TITLE
Spdlog Skips logging to file randomly

### ISSUE THREAD

**Issue by yasir-akram-byonyks** [gabime/spdlog#1880] opened 2021-03-17 09:19 UTC
Hi,

I am using spdlog logging module, it shows strange behaviors. Following are the behaviors. 

- Sometimes it didn't log anything to file.
- Sometimes, it skips logging some line to file.
- Sometimes it stops logging during the execution.
- If the process is terminated, it didn't log the last lines to the file.

NOTE: I am logging data to file every 10 Miliseconds.

**Comment by gabime** [comment] 2021-03-17 11:34
please see flush policy https://github.com/gabime/spdlog/wiki/7.-Flush-policy

**Comment by yasir-akram-byonyks** [comment] 2021-03-17 16:34
Hi,
Thanks for the help, but this only covers point 4. Please guide me with the solutions for the first 3 points.

Thanks

**Comment by gabime** [comment] 2021-03-17 19:13
Please provide sample code

**Comment by yasir-akram-byonyks** [comment] 2021-03-18 12:13
The same code works fine, but sometimes, I counter these behaviors. 

**void shareLogger(std::shared_ptr<spdlog::logger>, std::shared_ptr<spdlog::logger>, std::shared_ptr<spdlog::logger>, std::shared_ptr<spdlog::logger>)**{
    this->_IpcLogger = ipc;
    this->_StatusLogger = status;
    this->_ValueLogger = value;
    this->_CompleteLogger = complete;
}
void intializeLogger(){
try
    {
        _IpcLogger = spdlog::basic_logger_mt("Ipc Logger", logPath() + FOLDER_NAME + IPC_FILE_NAME);
        _IpcLogger->info(",Host,state,Message,Direction,Host,MsgType,Priority");
        _StatusLogger = spdlog::basic_logger_mt("Status Logger", logPath() + FOLDER_NAME + STATUS_FILE_NAME);
        _ValueLogger = spdlog::basic_logger_mt("Value Logger", logPath() + FOLDER_NAME + VALUES_FILE_NAME);
        _ValueLogger->info(",Host,state,Message,Direction,Host,MsgType,Priority");
        _CompleteLogger = spdlog::basic_logger_mt("Complete Logger", logPath() + FOLDER_NAME + COMPLETE_FILE_NAME);
    }
    catch (const spdlog::spdlog_ex &ex)
    {
        std::cout << ex.what() << std::endl;
    }

}

**Comment by gabime** [comment] 2021-03-18 13:48
Nothing interesting here, except maybe the "IPC_FILE_NAME".. What's that ? Some kind of networked/named-piped file ?

**Comment by gabime** [comment] 2021-03-27 08:22
cant reproduce. closing

**Closed by gabime** 2021-03-27 08:22 UTC

**Comment by yasir-akram-byonyks** [comment] 2021-03-29 09:20
Please reproduce,
We are working on Debian 10.7, 
Machine specs

1 GB RAM
16 GB ROM

**Comment by tt4g** [comment] 2021-03-29 13:13
Try to call `spdlog::shutdown()` before the application exit.
