### ISSUE TITLE
ubuntu call dlopen() Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Mr-jiayunfei** [gabime/spdlog#1534] opened 2020-04-28 09:45 UTC
Hello, I encapsulated spdlog as a dynamic library, it can be used normally on Windows, but an error occurs on ubuntu, prompting a segfault, but the strange thing is that using spdlog directly with exe is normal, I do n’t know which step Something went wrong

**Comment by Mr-jiayunfei** [comment] 2020-04-28 09:48
use “ auto async_file = spdlog::basic_logger_mt<spdlog::async_factory>("async_file_logger", "logs/async_log.txt"); “ and ” spdlog::flush_every(std::chrono::seconds(2)); “ will show segmentation fault(core dumped)

**Comment by zh1cheng** [comment] 2020-04-28 10:51
Encountered the same issue here on Ubuntu. Use SPDLOG in dynamic library. The same application run on Windows no crash. But on Ubuntu it crashes. My code crashes when this function spdlog::daily_file_sink_mt been called.

**Comment by tt4g** [comment] 2020-04-28 11:09
Please provide code that can reproduce the problem.

**Comment by zh1cheng** [comment] 2020-04-28 11:18
Below is my code. Run in exe on Ubuntu, works fine; Compile this code into dynamic library(so) file, it crashes.

spdlog::set_async_mode(65536);
spdlog::set_level((spdlog::level::level_enum)2);
spdlog::set_pattern("[%H:%M:%S.%f] %t %L %v%E");
spdlog::logger log = spdlog::daily_file_sink_mt("buy", "./log/buy", 0, 0, true);  **<- Crashed here**

**Comment by tt4g** [comment] 2020-04-28 11:35
@zh1cheng spdlog v1.4.2 or earlier, `spdlog::daily_file_sink_mt` cannot create directory.
If `./log` directory does not exist, must be create it yourself.

This feature is supported in spdlog v1.5.0 and above.

https://github.com/gabime/spdlog/releases/tag/v1.5.0:

> Auto create the required logging directories if they do not exist

What spdlog version which your use?
`spdlog::set_async_mode()` has dropped since spdlog v1.x.

I found this API in v0.17.0 but this version too old.

https://github.com/gabime/spdlog/blob/560df2878ad308b27873b3cc5e810635d69cfad6/include/spdlog/spdlog.h#L64-L67

I recommend bump spdlog version.

**Comment by zh1cheng** [comment] 2020-04-28 11:38
@tt4g Thanks for your reply. Let try to compile  with the newer version, and update you again. The library I am using was two years ago.

**Comment by gabime** [comment] 2020-04-28 20:38
@Mr-jiayunfei Please provide a minimal example to reproduce or close this issue.

**Comment by zh1cheng** [comment] 2020-04-29 05:27
Hi Guys,
After some troubleshooting, I found out that when call the function dlopen() to load the dynamic library, need use the option RTLD_GLOBAL. if not, some static objects in the library seems to be affected and caused the crash.

I solved my problem by setting RTLD_GLOBAL when call dlopen() to load the dynamic library. 

Hope this helps for those facing similar problem.

**Comment by gabime** [comment] 2020-04-29 10:15
@z1 Thanks for the tip. Might be worth to add to the wiki somewhere for future users.

**Closed by gabime** 2020-04-29 10:15 UTC

**Comment by Mr-jiayunfei** [comment] 2020-04-30 02:03
@zh1cheng ,Thank you very much for your help, I used your method and the problem was solved。

**Comment by Mr-jiayunfei** [comment] 2020-04-30 02:05
@tt4g Sorry, because some things did not have time to reply to your message yesterday, the problem has been solved now, thank you

**Comment by gabime** [comment] 2020-04-30 10:12
@Mr-jiayunfei Can you please provide here the code that fix the problem? I want to add it to the wiki docs.
