### ISSUE TITLE
daily_file_sink don't work as expected

### ISSUE THREAD

**Issue by LeeGaning** [gabime/spdlog#726] opened 2018-06-12 09:03 UTC
```c
struct custom_daily_file_name_calculator
{
    static spdlog::filename_t calc_filename(const spdlog::filename_t& filename)
    {
        std::tm tm = spdlog::details::os::localtime();
        spdlog::filename_t basename, ext;
        std::tie(basename, ext) = spdlog::details::file_helper::split_by_extenstion(filename);
        fmt::MemoryWriter w;
        w.write("{}_{:04d}{:02d}{:02d}{}", basename, tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, ext);
        return w.str();
    }
};

int main(int argc, char *argv[]) {
    using sink_type = spdlog::sinks::daily_file_sink<std::mutex,custom_daily_file_name_calculator>;
    spdlog::set_error_handler([](const std::string &msg) {
        std::cerr << "spdlog err handler: " << msg << std::endl;
    });
    //calculate filename (time based)
    std::string basename = "logs/udpserv.txt";
    auto main_logger = spdlog::create<sink_type>("main_logger", basename, 0, 0);
    spd::set_level(spd::level::debug);
    main_logger->info("Welcome to spdlog!");
    ......
}
```
```shell
-rw-r--r-- 1 root root 301M May 27 00:00 udpserv_20180526.log
-rw-r--r-- 1 root root 303M May 28 00:00 udpserv_20180527.log
-rw-r--r-- 1 root root 309M May 29 00:00 udpserv_20180528.log
-rw-r--r-- 1 root root 324M May 30 00:00 udpserv_20180529.log
-rw-r--r-- 1 root root 337M May 31 00:00 udpserv_20180530.log
-rw-r--r-- 1 root root 341M Jun  1 00:00 udpserv_20180531.log
-rw-r--r-- 1 root root 345M Jun  2 00:00 udpserv_20180601.log
-rw-r--r-- 1 root root 347M Jun  3 00:00 udpserv_20180602.log
-rw-r--r-- 1 root root 343M Jun  4 00:00 udpserv_20180603.log
-rw-r--r-- 1 root root 710M Jun  6 00:00 udpserv_20180604.log
-rw-r--r-- 1 root root 359M Jun  7 00:00 udpserv_20180606.log
-rw-r--r-- 1 root root 359M Jun  8 00:00 udpserv_20180607.log
-rw-r--r-- 1 root root 365M Jun  9 00:00 udpserv_20180608.log
-rw-r--r-- 1 root root 373M Jun 10 00:00 udpserv_20180609.log
-rw-r--r-- 1 root root 378M Jun 11 00:00 udpserv_20180610.log
-rw-r--r-- 1 root root 645M Jun 12 16:47 udpserv_20180611.log
```
I want to  generate a new filename every day at 00:00;but sometimes It don't work as expected;
20180605->daily_file_sink don't  generate a new filename；
20180612->daily_file_sink don't  generate a new filename；

**Comment by gabime** [comment] 2018-06-12 09:09
Maybe there was no log activity on those dates? It creates new file only when the logger actually writes something to the file.

**Comment by LeeGaning** [comment] 2018-06-16 12:52
![image](https://user-images.githubusercontent.com/12764014/41498708-d812bf3a-71a6-11e8-86bd-a8208a5e8577.png)

As the image,Log activity is OK.

**Comment by gabime** [comment] 2018-06-16 13:01
r u using threads?

**Comment by LeeGaning** [comment] 2018-06-16 13:04
Yes,I create the log at Main threads，worker threads use it by  get_logger

**Comment by gabime** [comment] 2018-06-16 13:51
please provide compiler and os details.

**Comment by LeeGaning** [comment] 2018-06-16 15:17
```shell
$g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
```
```shell
$uname -a
Linux  3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
The OS is *Ubuntu 14.04.2* with libpthread-2.19.so
```shell
g++ -Wall -O2 -std=c++11 -I /home/ligy/tmp/udpserv/include  -lpthread -lmysqlclient -c -o main.o main.cpp 
```

**Comment by gabime** [comment] 2018-06-16 16:13
I suspect it might be caused by not using steady clock. Could you please change line 62 in common.h to 
```c++
using log_clock=std::chrono_steady_clock;
```
 and see if it solves the problem after running for a few days?

**Comment by gabime** [comment] 2018-07-12 22:45
Fixed in v1.x branch

**Closed by gabime** 2018-07-12 22:45 UTC
