### ISSUE TITLE
async log doesn't work in multithreaded environments

### ISSUE THREAD

**Issue by dyoungworth** [gabime/spdlog#1068] opened 2019-04-24 16:56 UTC
Hi gabime, first of all, thank you for all your work on spdlogs!  Now on to the issue:

I noticed async rotating logs don't seem to work in a multi-thread environment:

```
auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("trace.json", 1000000, 10);
auto trace = spdlog::create_async("tr", file_sink, 4096);
trace->flush_on(spdlog::level::info);

pid_t pidS = fork();
if (pidS == 0) {
trace->info("child thread");
return 0;
}
trace->info("parent thread");
```

In this example, I only see "parent thread" in the log.  However, a non-async seems to work.  If I replace the first two lines with:
`
auto trace = spdlog::rotating_logger_mt("tr", trace.json", 1000000, 10);
`

I get both outputs

**Comment by gabime** [comment] 2019-04-24 17:07
duplicate of https://github.com/gabime/spdlog/issues/748

**Closed** 2019-04-24 22:29 UTC
Labels: duplicate
