### ISSUE TITLE
Use of undeclared identifier 'InetPtonA'

### ISSUE THREAD

**Issue by afeiyoo** [gabime/spdlog#3303] opened 2024-12-30 14:46 UTC
I compiled the example under spdlog, but it prompted me with an error: Use of undeclared identifier 'InetPtonA'. 
I use qmake to manage the project

Please help me

System: Windows 11
IDE: Qt Creator 12.0.2
Compiler: Mingw 7.3.0 64-bit

**Comment by gabime** [comment] 2024-12-30 15:04
duplicate of #2225

**Closed as completed** 2024-12-30 15:04 UTC
