### ISSUE TITLE
log rotate fails on specific windows computer

### ISSUE THREAD

**Issue by susundberg** [gabime/spdlog#2347] opened 2022-04-22 06:55 UTC
Dear all,

The case is following: we are using spdlog (thanks!) for our QT user-software project. Its working fine - on linux and windows laptops. Until yesterday. A team member was testing the software with Panasonic Thoughbook - and during investigation of another bug i found out that we are missing logs. This has never happened on another Windows system, or any other system ( DEV uses linux on some machines ). So i am pretty confident we are not doing it totally wrong.

Well digging deeper looks like the issue comes when rotating the file. The "<path>/log.txt" gets truncated when size gets larger than set size, but no log.1.txt gets created.

ProcessMonitor output of relevant lines (i am unwilling to attach full file as scare of privacy leak) is attached, but what it looks like to me that it hits the rotate function, and the rotate fails -- twice:

```
"14.26.42,4478337","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.1.txt","NAME NOT FOUND","Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"14.26.42,4479056","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a"
"14.26.42,4479814","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"14.26.42,5489689","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.1.txt","NAME NOT FOUND","Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"14.26.42,5490495","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a"
"14.26.42,5491168","MYAPP.exe","8396","CreateFile","C:\Users\PRIVACY_PROTECTED\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"

```

I did try to turn of Microsoft-Defender virus protection but it did no help. The attached  log is from full event log with filtering: 
```
 grep 'PRIVACY_PROTECTED' Logfile_rotate_failed_2.CSV 
```
(where PRIVACY_PROTECTED is actually few folders that contain some information i am not willing to write here publicly).

Our sink is declared as:
```
_log_setup.sink_file = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(
                filename_use.c_str(), file_max_size_kb * 1024, file_max_count);
```
And our tweaks are:
```
#define SPDLOG_WCHAR_FILENAMES
```

On the console i see notification that the rotation has failed (timestamp from different run, as i had to recompile to get stdout visible):
```
[*** LOG ERROR #0001 ***] [2022-04-21 15:05:46] [model] {rotating_file_sink: failed renaming C:\Users\PRIVACY_PROTECTED\logs\log.txt to C:\Users\PRIVACY_PROTECTED\logs\log.1.txt: Permission denied}
```

Any ideas what could be going on here? Thanks for your time.

**Comment by susundberg** [comment] 2022-04-22 06:57
[filt.txt](https://github.com/gabime/spdlog/files/8537651/filt.txt)

The attachment file of event logs from proccess monitor.

**Comment by tt4g** [comment] 2022-04-22 10:27
On Windows OS, file renaming may fail due to anti-virus software or `System` processes opening files.

If the file is closed, the rename succeeds. spdlog will sleep when the operation fails and then retry.

https://github.com/gabime/spdlog/blob/b3ce5ed379ed01d9147b079e605e84dd408a0c19/include/spdlog/sinks/rotating_file_sink-inl.h#L124-L130

As far as your attached `filt.txt`, `SHARING VIOLATION` is occurring, so in both cases some process is opening the file.
There is nothing spdlog can do about it because it is caused by another process.

Use the Resource Monitor to investigate another process that is opening the log file.

**Comment by susundberg** [comment] 2022-04-22 10:36
Thanks for your reply and debug suggestion. Will check next (next week, due the particular machine offline at the office). And i do I agree that the behavior is exactly as written on the code -- and on the filt.txt the timestamps very finely matches the 100ms sleep.

If that suites you i will return with the root cause to this ticket and close it afterwards. I expect no reply for this.

**Comment by susundberg** [comment] 2022-04-26 10:48
I am returning to the ticket without any luck. I am unable to find out what is causing the root issue. "Resource Monitor" shows no other process using the logfile (like there should not be) - and i turned off the defender real-time protection (-> absense of MsMpEng.exe on the ProcessMonitor).

Here is another example, full events capture, with filtered
```
 grep "My App Name.logs" Logfile_no_virus.CSV > filtered_2.txt
```
That is; i try to filter in only the events that uses the folder where the logging is directed to. I have no idea wtf is blocking the usage; my only guess is that the toughbook would have some weirdly slow disk write or similar.


```
"13.06.15,4237903","MyAppName.exe","11732","CloseFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS",""
"13.06.15,4238372","MyAppName.exe","11732","IRP_MJ_CLOSE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS",""
"13.06.15,4239318","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.1.txt","NAME NOT FOUND","Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"13.06.15,4240530","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a"
"13.06.15,4241869","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"13.06.15,4506156","System","4","FASTIO_ACQUIRE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS","EndingOffset: 20 480"
"13.06.15,4506336","System","4","FASTIO_RELEASE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS",""
"13.06.15,4713571","System","4","FASTIO_ACQUIRE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS","EndingOffset: 24 576"
"13.06.15,4713890","System","4","FASTIO_RELEASE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS",""
"13.06.15,4928745","System","4","FASTIO_ACQUIRE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS","EndingOffset: 8 192"
"13.06.15,4929081","System","4","FASTIO_RELEASE_FOR_MOD_WRITE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS",""
"13.06.15,5290540","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.1.txt","NAME NOT FOUND","Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"13.06.15,5295050","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a"
"13.06.15,5298604","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SHARING VIOLATION","Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"13.06.15,5302032","MyAppName.exe","11732","QueryOpen","C:\Users\MyUserName\AppData\Roaming\My App Name\logs","FAST IO DISALLOWED",""
"13.06.15,5303974","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"13.06.15,5304695","MyAppName.exe","11732","QueryBasicInformationFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs","SUCCESS","CreationTime: 21/04/2022 11.55.32, LastAccessTime: 26/04/2022 13.06.15, LastWriteTime: 26/04/2022 13.05.39, ChangeTime: 26/04/2022 13.05.39, FileAttributes: D"
"13.06.15,5305123","MyAppName.exe","11732","CloseFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs","SUCCESS",""
"13.06.15,5305615","MyAppName.exe","11732","IRP_MJ_CLOSE","C:\Users\MyUserName\AppData\Roaming\My App Name\logs","SUCCESS",""
"13.06.15,5308108","MyAppName.exe","11732","CreateFile","C:\Users\MyUserName\AppData\Roaming\My App Name\logs\log.txt","SUCCESS","Desired Access: Generic Write, Read Attributes, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Overwritten"
```

**Comment by tt4g** [comment] 2022-04-26 11:27
`C:\Users\MyUserName\AppData\Roaming` (environment variable `%APPDATA%`) folder may be managed by a Windows Roaming User Profile.
Any changes in this folder may be very slow to read/write and behave weirdly due to synchronization with Active Directory.

Can you see if the problem can be fixed by saving the log files in another folder?

**Closed** 2022-04-27 09:16 UTC
