### ISSUE TITLE
Can I now flush logs when crash occurs?

### ISSUE THREAD

**Issue by VladimirBalun** [gabime/spdlog#1659] opened 2020-08-31 13:34 UTC
I saw an issue: https://github.com/gabime/spdlog/issues/55
I want to ask you, do you add this feature for project now?

**Comment by gabime** [comment] 2020-08-31 14:40
Duplicate of #1607 
Not sure if there is a reliable way to do it though.

**Closed** 2020-09-07 00:08 UTC
