### ISSUE TITLE
watching thread for configuration change

### ISSUE THREAD

**Issue by mipac** [gabime/spdlog#165] opened 2016-01-13 14:51 UTC
A configuration file for the loggers would be very useful
Changing the conf while process is running too :)
An option to start a thread watching for conf file change would be perfect:
- default behavior : the new conf is applied
- a user "callback" is called if supplied

**Comment by gabime** [comment] 2016-01-13 19:11
Duplicate of #162

**Closed by gabime** 2016-01-13 19:11 UTC
