### ISSUE TITLE
Weird output when using daily logger

### ISSUE THREAD

**Issue by chaarirami** [gabime/spdlog#2535] opened 2022-11-04 12:09 UTC
After few days of using a daily logger, the output in the file seems to be corrupt. I attached an example of the file below.
[system_2022-11-03.log](https://github.com/gabime/spdlog/files/9937917/system_2022-11-03.log)
I'm unsure on how this happened, any recommendation or insight would be appreciated.

**Comment by tt4g** [comment] 2022-11-04 21:13
We do not know how you are using spdlog.
Without minimal code to reproduce the problem, it is difficult to guess why this happened.

**Comment by tt4g** [comment] 2022-11-04 21:14
To take a wild guess, if two processes write logs to a file at the same time, the contents of the file will be corrupted.

**Comment by chaarirami** [comment] 2022-11-07 09:28
Thank you for your quick reply.
This is the function we are using to setup different daily loggers:
```C++
inline static void setupDailyLogger(const std::string &folder,
                                    const std::string &fileName,
                                    const std::string &fileExtension,
                                    const std::string &loggerName,
                                    const std::string &loggerPattern,
                                    const std::string &loggerHeader,
                                    const int &hour,
                                    const int &minute) {
    if (!spdlog::get(loggerName)) {
        auto loggerPath = folder + "/" + fileName + fileExtension;
        /* Check if header exists or not. This is done by iterating over the folder and checking each file if it contains the type and date of the file we want to create. */
        bool headerExists = false;
        // check if folder exists. If not, create it
        if (!std::filesystem::exists(folder)) {
            std::filesystem::create_directories(folder);
        }
        for (const auto &entry : std::filesystem::directory_iterator(std::filesystem::path(folder))) {
            if ((entry.path().filename().string().find(fileName) != std::string::npos) && (entry.path().filename().string().find(utils::getCurrentDate()) != std::string::npos)) {
                headerExists = true;
                break;
            }
        }
        /* Create the logger */
        auto dailyLogger = spdlog::daily_logger_mt(loggerName, loggerPath, hour, minute);
        dailyLogger->flush_on(spdlog::level::info);
        if (!headerExists) {// header does not exist, create it
            dailyLogger->set_pattern("%v");
            dailyLogger->info(loggerHeader);
        }
        dailyLogger->set_pattern(loggerPattern);
    }
}
```
Then we are logging the data into the files using
```C++
auto logger = spdlog::get(loggerName);
if (logger) {
     logger->info(textToLog);
}
```
We are unsure on how to exactly replicate the same mistake. Any hints or suggestions would be much appreciated.

**Comment by tt4g** [comment] 2022-11-07 10:28
Are multiple processes running at the same time?
Or `textToLog` is not a correctly null-terminated `char*`.

**Comment by chaarirami** [comment] 2022-11-07 10:42
I will check that. Per default, only one process at a time should be running.
As for your second point, can you please tell me how to check whether `textToLog` is correctly null-terminated or not? `textToLog` is of type `std::string`.
Thank you.

**Comment by tt4g** [comment] 2022-11-07 11:44
If you are not writing to a single file from more than one process, the `system_2022-11-03.log` shows that the broken line is outputting 0x00 (null-terminated) first, so I assume you are passing an invalid `char*` (or `std::string` like object).

> As for your second point, can you please tell me how to check whether `textToLog` is correctly null-terminated or not?

There is no reliable way to verify that null-terminated is correct.
For example, some I/O APIs return `char*`, but null-terminated is not guaranteed (or must be null-terminated by the developer).
it is always the developer's responsibility to null-terminate a `char*` read in I/O, but if this responsibility is not fulfilled, an incorrect `char*` will be present in the application.

And `std::string::string(const CharT*)` does not work correctly when passing non-null-terminated characters.

> 5) Constructs the string with the contents initialized with a copy of the null-terminated character string pointed to by s. The length of the string is determined by the first null character. The behavior is undefined if [s, s + Traits::length(s)) is not a valid range (for example, if s is a null pointer). This constructor is not used for [class template argument deduction](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction) if the Allocator type that would be deduced does not qualify as an allocator. (since C++17)
>
> https://en.cppreference.com/w/cpp/string/basic_string/basic_string

Usually it is safe to use only the literal `char*`.
However, since the application reads data externally via I/O in most cases, it is possible that somewhere it is generating characters that are not null-terminated.

EDIT: Passing the wrong character length as the second argument to `std::string::string(const CharT*, size_type)` will also result in a broken `std::string`.

> Constructs the string with the first count characters of character string pointed to by s. s can contain null characters. The length of the string is count. The behavior is undefined if [s, s + count) is not a valid range.
>
> https://en.cppreference.com/w/cpp/string/basic_string/basic_string

**Comment by chaarirami** [comment] 2022-11-07 13:17
Thank you, I'll try to check if the logged data is correctly null-terminated.

Furthermore, we managed to decode the data by reading it bitwise and then decoding it. So I'm guessing that there was an error when decoding the information.
This can be done using the following snippet:
```python
body = obj.get()['Body'].read()
df = pd.read_csv(io.StringIO(body.decode('ISO-8859-1')),sep =';',on_bad_lines='skip', names=header) 
```
Does this give some new insights on how to solve this problem?

**Comment by tt4g** [comment] 2022-11-07 13:24
Since it looks like Python code, there may be a problem in the Python code, or there may be a problem at the point where the data is transferred from Python to C++.

**Comment by chaarirami** [comment] 2022-11-07 13:41
The file I originally attached was not modified by python code at all. So only the C++ snippet wrote to the file. So I guess that there is an issue with either multiple processes accessing the file at the same time or broken strings.

**Closed as completed** 2023-01-03 22:45 UTC
