### ISSUE TITLE
Logger created with vector of one sink is 1000x slower than create<sink>

### ISSUE THREAD

**Issue by sourcedelica** [gabime/spdlog#252] opened 2016-07-29 02:19 UTC
For some reason I am seeing a logger configured using a vector of sinks (containing only one `rotating_file_sink_st`) as 1000x slower than a logger created directly using `spdlog::create<rotating_file_sink_st>`.  I'm using async mode.  That doesn't seem right.

**Comment by gabime** [comment] 2016-07-29 05:41
how did you bench?can you post it please?

**Comment by sourcedelica** [comment] 2016-07-29 14:17
Will do.  I need to untangle some code first to put together a minimal
reproducer.

But in the meantime, it looks like it's the combination of forceFlush =
true and using a container.

Vector,  forceFlush = true:  spdlog->info string 208673us

Vector, forceFlush = false:  spdlog->info string   1468us

forceFlush = true: spdlog->info string  189us

forceFlush = false: spdlog->info string    176us


-- Eric

**Comment by sourcedelica** [comment] 2016-07-29 14:45
Does `forceFlush` make logging synchronous?

**Comment by gabime** [comment] 2016-07-29 17:14
No, flush is done  in the back thread. force_flush=true could result in a big queue over time, which would block the caller when the queue gets full.. but very strange results regarding the vector..

Please  provide some additional info:
- which sinks are being tested? 
- what is the max size of the queue ?
- platform and compiler

**Comment by sourcedelica** [comment] 2016-07-29 21:01
Here you go:
- Sinks: `rotating_file_sink_mt` and `st`. 
- The queue size is 1024 * 1024.   Raising it to 1024 * 1024 * 1024 doesn't change the performance.
- Platform is Fedora 22, GCC 5.1.1

You'll see one line commented out that adds a stdout sink to the container.  The problem manifests without that sink actually in the container.   The constants commented with "Options that most impact the performance in this test" are set to the values that cause the big jump in slowness.

```
#include <string>
#include <iostream>
#include <iomanip>
#include <unistd.h>
#include "spdlog/spdlog.h"

using namespace std;

// Make sure this is less than Logger::DefaultQueueSize
constexpr long Iterations = 1000;
// Amount of time to wait after each round to allow queue to drain
constexpr long SleepUsec = 100000;

// Options that most impact the performance in this test
constexpr bool SingleThreaded = true;
constexpr bool UseContainer = true, ForceFlush = true;
constexpr size_t QueueSize = 1024 * 1024;

int removeFile(const string filename)
{
    return std::remove(filename.c_str());
}

void time(const string &testName, std::function<void(void)> func)
{
    auto start = chrono::steady_clock::now();

    for (int i = 0; i < Iterations; i++) {
        func();
    }

    auto elapsed = chrono::steady_clock::now() - start;
    long elapsedUs = chrono::duration_cast<chrono::microseconds>(elapsed).count();
    cout << setw(30) << testName << setw(7) << elapsedUs << "us" << endl;

    usleep(SleepUsec);  // Wait for queue to drain
}


template <typename F, typename C>
std::shared_ptr<spdlog::logger> createPrimaryLogger(
        const std::string &loggerName,
        const std::string &baseFilename,
        const std::string &extension,
        const bool logToFile,
        const bool useContainer,
        const unsigned level,
        const size_t maxSize,
        const size_t maxFiles,
        const bool forceFlush)
{
    std::shared_ptr<spdlog::logger> spdLogger;

    if (!logToFile && !useContainer) {
        throw std::invalid_argument("One or both of logToFile and useContainer must be true");

    } else if (logToFile && useContainer) {  // TODO: this combination is 3 orders of magnitude slower with forceFlush
        std::vector<spdlog::sink_ptr> sinks;  // and one order of magnitude slower without
        sinks.push_back(std::make_shared<F>(baseFilename, extension, maxSize, maxFiles, forceFlush));
//        sinks.push_back(std::make_shared<C>());
        spdLogger = std::make_shared<spdlog::logger>(loggerName, begin(sinks), end(sinks));

    } else if (logToFile) {
        spdLogger = spdlog::create<F>(loggerName, baseFilename, extension, maxSize, maxFiles, forceFlush);
    } else {
        spdLogger = spdlog::create<C>(loggerName);
    }

    spdLogger->set_level(static_cast<spdlog::level::level_enum>(level));
    return spdLogger;
}

std::shared_ptr<spdlog::logger> createPrimaryLogger(
        const std::string &loggerName,
        const std::string &baseFilename,
        const std::string &extension,
        const bool logToFile,
        const bool useContainer,
        const unsigned level,
        const bool singleThreaded,
        const size_t maxSize,
        const size_t maxFiles,
        const size_t queueSize,
        const bool forceFlush,
        const std::chrono::milliseconds flushIntervalMs,
        const bool blockOnFullQueue)
{
    auto overflowPolicy = blockOnFullQueue ? spdlog::async_overflow_policy::block_retry
                                           : spdlog::async_overflow_policy::discard_log_msg;
    spdlog::set_async_mode(queueSize, overflowPolicy, nullptr, flushIntervalMs);

    typedef spdlog::sinks::rotating_file_sink_mt file_mt;
    typedef spdlog::sinks::rotating_file_sink_st file_st;
    typedef spdlog::sinks::stdout_sink_mt console_mt;
    typedef spdlog::sinks::stdout_sink_st console_st;

    if (singleThreaded) {
        return createPrimaryLogger<file_st, console_st>(loggerName, baseFilename, extension, logToFile, useContainer,
                                                        level, maxSize, maxFiles, forceFlush);
    } else {
        return createPrimaryLogger<file_mt, console_mt>(loggerName, baseFilename, extension, logToFile, useContainer,
                                                        level, maxSize, maxFiles, forceFlush);
    }
}

shared_ptr<spdlog::logger> init()
{
    static bool initialized;
    static shared_ptr<spdlog::logger> spd;
    static const unsigned level = 2;
    static const size_t fileSize = 1024 * 1024 * 1024, numFiles = 5;
    static const bool logToFile = true;
    static const bool blockOnFullQueue = false;
    static const std::chrono::milliseconds flushIntervalMs(1);

    if (!initialized)
    {
        const string logDir = "../log";
        const string logBase = logDir + "/spdlog_reproducer";
        removeFile(logBase + ".log");
        spd = createPrimaryLogger("primary", logBase, "log", logToFile, UseContainer,
                                  level, SingleThreaded, fileSize, numFiles, QueueSize,
                                  ForceFlush, flushIntervalMs, blockOnFullQueue);

        cout << "Using " << Iterations << " iterations" << endl;
        initialized = true;
    }

    return spd;
}

int main()
{
    auto spd = init();

    time("spdlog->info string", [&spd]{ spd->info("spdl"); });
}
```

**Comment by gabime** [comment] 2016-07-30 00:57
The problem is that the line
```c++
spdLogger = std::make_shared<spdlog::logger>(loggerName, begin(sinks), end(sinks));
```
actually creates a synchronous logger instead of  asynchronous.

If can be fixed by:
```c++
// ask spdlog to create a looger according to the global settings
// (i.e. async logger because set_async_mode(..) was previously called)
spdLogger = spdlog::create(loggerName, begin(sinks), end(sinks));
```

 
Alternatively, one could create async logger directly without relying on spdlog's factory functions:
```c++
spdLogger = std::make_shared<spdlog::async_logger>(loggerName, begin(sinks), end(sinks), QueueSize);
```

**Comment by sourcedelica** [comment] 2016-07-30 02:01
Ahhh - much better.   Thanks!


-- Eric

**Closed** 2016-07-30 02:29 UTC
