### ISSUE TITLE
spdlog's format lib doesn't support user defined streaming operators anymore

### ISSUE THREAD

**Issue by gnzlbg** [gabime/spdlog#247] opened 2016-07-21 16:06 UTC
The following code used to work but now is broken:

```c++
struct TT {
  int i;
  template<typename OStream>
  friend OStream& operator<<(OStream& os, TT const& j) {
    os << j.i;
    return os;
  }
};
fmt::print("a {} b {}", TT{2}, 3);
```

**Comment by gnzlbg** [comment] 2016-07-21 16:21
That will fix the problem, until a new version of fmtlib breaks spdlog again. The long term fix is to:

1) Require fmtlib as a dependency (instead of shipping an outdated copy).
2) Have a header file through which spdlog includes fmtlib and that deals with different fmtlib versions. 

Any project using both spdlog and fmtlib needs to dance around spdlog including its own outdated version. This is unnecessary.

**Comment by vitaut** [comment] 2016-07-21 16:31
The problem here is not that fmt shipped with spdlog is out of date (it's actually newer than the last released fmt version), but rather that it doesn't include optional headers such as `fmt/ostream.h`.

**Comment by vitaut** [comment] 2016-07-21 16:35
That said, to prevent client breakage I recommend sticking to a released version of fmt in spdlog. I'll be happy to merge critical fixes into the release branch if necessary.

**Comment by gnzlbg** [comment] 2016-07-21 16:57
> The problem here is not that fmt shipped with spdlog is out of date (it's actually newer than the last released fmt version),

I had a project using fmtlib master branch. When I added spdlog to that project I had to switch to an "out of date" version of fmtlib through spdlog because I didn't manage to use both versions at the same time. 

I would rather just let the user choose which fmtlib version to use and deal with incompatibilities between different versions internally within spdlog (or just `#pragma error "your fmtlib version is too old/too new"`). 

Basically the `fmt.h` of spdlog would just be a:

```c++
#pragma once
/// \file
/// Includes fmtlib
#include <fmt/format.h>

#if FMT_LIB_VERSION > 2
  #include <fmt/ostream.h>
#endif

// deal with other possible changes here
```

That allows supporting different fmtlib versions within spdlog easily. Those tracking master can commit small workarounds easily in case of incompatibilities, and when a new fmtlib version is released those workarounds get moved into a version macro.

The current status quo of "hoping" that users don't include a different fmtlib version before the spdlog one with possibly subtle incompatibilities is really brittle.

**Comment by gabime** [comment] 2016-07-21 21:46
@gnzlbg Seem good idea - having somekind of `"fmt.h"` proxy header in spdlog..

By default, I still want fmt to be bundled with spdlog releases, so maybe something like this in the new fmt.h:

```c++

#if not defined(FMTLIB_STANDALONE) //use spdlog's copy 
#define FMT_HEADER_ONLY
#define FMT_USE_WINDOWS_H 0
#include <spdlog/fmt/format.h>
#else
#include <fmt/format.h> //use external copy provided by the user
#endif
```

**Comment by rob-p** [comment] 2016-07-21 21:47
Just to be clear about the existing bug report, using the current `spdlog` version (*with* it's bundled version of `fmt`) will cause user-supplied stream insertion operators to fail?

**Comment by gabime** [comment] 2016-07-21 21:58
Depends on the demand of this feature. I rarely encountered (until today) code that logs custom classes using the operator<<,  so I decided to remove it while removing other ostream support in spdlog.. but I could be wrong. 

The problem is that it adds to the compilation time as everything is header only (in addition ostream.cc includes printf.h for some reason. @vitaut could this dependency be removed ?)

**Comment by rob-p** [comment] 2016-07-21 22:03
I see.  I do make use of this feature in a few places, so I'm glad to have stumbled upon this report before attempting to upgrade to the latest version.  I understand the desire to default to the most common case, but perhaps there could at least be some way of re-enabling support for this (e.g. via a specific compilation flag).

**Comment by vitaut** [comment] 2016-07-21 22:06
@gabime Compile time doesn't have to be affected if you follow the fmt approach and require users include `fmt/ostream.h` (or its spdlog wrapper) for `std::ostream` support. I'm sure I can do something about the dependency on `printf.h`.

**Comment by gabime** [comment] 2016-07-21 22:23
@vitaut Right that would solve it (as long as the user remembers to include `<spdlog/fmt/ostream.h> `of course).

@rob-p So using this approach, in order to keep using ostream you would need to include `<spdlog/fmt/ostream.h>`

**Comment by gabime** [comment] 2016-07-22 00:49
@vitaut To make this work the `#include` statements in the` format.cc` and `ostream.cc` have to be removed in header only configuration (otherwise fmt/format.h and fmt/printf.h cannot be found easily, and the are not really needed in the header only configuration anyway )

Maybe you could wrap with something like 
```c++
!defined(FMT_HEADER_ONLY) //no need to include in header only
#include "fmt/format.h"
#include "fmt/printf.h"
#endif
```

**Comment by gnzlbg** [comment] 2016-07-22 07:36
> So using this approach, in order to keep using ostream to log custom types you would need to include <spdlog/fmt/ostream.h>

That way those who don't need the feature don't pay for it. Including `ostream` is not something that everybody needs (and it is actually something some users want to avoid).

**Comment by gabime** [comment] 2016-07-22 16:22
I committed the needed changes in  0ae66b5b28f67c6b8da1f1b273020514ce198f47

Now the user can define SPDLOG_FMT_EXTERNAL to use his own version of fmtlib
(can be also be done in` tweakme.h`) .

Logging custom types using operator<< us supported too . 
The user will need to` #include <spdlog/fmt/ostr.h>` for this to work.

**Comment by gabime** [comment] 2016-07-26 01:38
fixed in https://github.com/gabime/spdlog/commit/0ae66b5b28f67c6b8da1f1b273020514ce198f47

**Closed** 2016-07-26 01:37 UTC

**Comment by vitaut** [comment] 2016-08-03 16:08
@gabime I've removed dependency from `printf.h` in https://github.com/fmtlib/fmt/commit/9dbb60c4c8019c0d851ce2e61f99cb5c74696369.

**Comment by gabime** [comment] 2016-08-04 16:02
@vitaut :+1:
