### ISSUE TITLE
MinGw on Windows failing during compile

### ISSUE THREAD

**Issue by tsteinholz** [gabime/spdlog#131] opened 2015-09-13 15:55 UTC
I am pretty sure I set this up correctly and it was working under Visual Studio on Windows and Linux. I create my build script with CMake and I have the Includes working. I am compiling with [MingGw 64bit](http://sourceforge.net/projects/mingw-w64/) but I also remeber 32 bit (default) not working for me either.

    In file included from ..../my_project/Include/spdlog/details/pattern_formatter_impl.h:36:0,
                 from ..../my_project/Include/spdlog/formatter.h:57,
                 from ..../my_project/Include/spdlog/sinks/base_sink.h:36,
                 from ..../my_project/Include/spdlog/logger.h:36,
                 from ..../my_project/Include/spdlog/spdlog.h:33,
                 from ..../my_project/Source/Public/Engine.h:5,
                 from ..../my_project/Source/Private/Engine.cpp:1:
    .../my_project/Include/spdlog/details/os.h: In function 'int spdlog::details::os::utc_minutes_offset(const tm&)':
    ..../my_project/Include/spdlog/details/os.h:170:52: error: 'GetDynamicTimeZoneInformation' was not declared in this scope
    auto rv = GetDynamicTimeZoneInformation(&tzinfo);

**Comment by gabime** [comment] 2015-09-15 22:13
Seems like duplicate of #85 
Please try adding thesuggested define

**Comment by tsteinholz** [comment] 2015-09-17 00:41
Solved by adding `-D_WIN32_WINNT=0x600` to the compile flags. Thank you @gabime

**Closed** 2015-09-17 00:41 UTC
